name: testing-reusable-workflows

on: push


jobs:
  dummy-dev:
    environment: dev
    name: deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from dev"
      - name: Generate Notice Annotations
        run: |
          text="This is a Notice"
          echo "::notice::$text"


  dummy-staging:
    environment: staging
    needs: dummy-dev
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from staging"

  dummy-production:
    environment: production
    needs: dummy-staging
    name: deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from production"