name: testing-reusable-workflows

on: push


jobs:
  dummy-dev:
    environment: dev
    name: deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: create string
        run: |
          MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo "::set-output name=content::$MY_STRING"
        id: my_string
      - name: display string
        run: |
          echo "The string is: ${{ steps.my_string.outputs.content }}"
          echo "::notice::The string is: ${{ steps.my_string.outputs.content }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Notice Annotations
        run: |
          git describe --tags --always
          text="$(git log --pretty=oneline $(git describe --tags --abbrev=0 @^)..@)"
          echo "::notice::List of commit to be deployed\nLet's go"
          echo "::notice::$text"

      - name: foo
        run: echo "hello from dev"


  dummy-staging:
    environment: staging
    needs: dummy-dev
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from staging"

  dummy-production:
    environment: production
    needs: dummy-staging
    name: deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from production"