name: testing-reusable-workflows

on: push


jobs:
  dummy-dev:
    environment: dev
    name: deploy to dev
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Notice Annotations
        run: |
          filename=temp.log
          git log --oneline $(git describe --tags --abbrev=0 @^)..@ >> $filename
          while read line; do
            echo "::notice::$line"
          done < $filename
          rm $filename

      - name: foo
        run: echo "hello from dev"


  dummy-staging:
    environment: staging
    needs: dummy-dev
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from staging"

  dummy-production:
    environment: production
    needs: dummy-staging
    name: deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from production"