name: testing-reusable-workflows

on: push


jobs:
  dummy-dev:
    environment: dev
    name: deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from dev"
      - name: Generate Warning Annotations
        run: |
         text="This is a Warning"
         echo "::warning file=app.js,line=1,col=5::$text"
      - name: Generate Info Annotations 1
        run: |
          text="This is an Info"
          echo "::info file=app.js,line=1,col=5::$text"
      - name: Generate Info Annotations 2
        run: |
          text="This is an other Info"
          echo "::info ::$text"

  dummy-staging:
    environment: staging
    needs: dummy-dev
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from staging"

  dummy-production:
    environment: production
    needs: dummy-staging
    name: deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from production"