name: testing-reusable-workflows

on: push


jobs:
  dummy-dev:
    environment: dev
    name: deploy to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Notice Annotations
        run: |
          git describe --tags --always
          text="$(git log $(git describe --tags --always --abbrev=0 @^)..@)"
          echo "::notice::$text"
          echo "::notice::hello there"
      - name: foo
        run: echo "hello from dev"

  dummy-staging:
    environment: staging
    needs: dummy-dev
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from staging"

  dummy-production:
    environment: production
    needs: dummy-staging
    name: deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "hello from production"